import * as electron from '@theia/core/electron-shared/electron';
import { AppUpdater, ProgressInfo, UpdateInfo, autoUpdater } from 'electron-updater';
import { mkdtempSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { FABI_FOX_DATA_URI } from './fabi-launcher-logo';
import { enforceMandatoryUpdate } from '../common/fabi-update-gate';

/** Stable public release endpoint generated by electron-builder. */
export const FABI_APP_UPDATE_URL = 'https://server.undefinedstudio.fr/fabi-updates/stable';

/**
 * Startup gate for the desktop application.
 *
 * The IDE surface is created only after this gate reports that no update is
 * available. Once electron-updater has authenticated a newer release, the gate
 * intentionally never resolves: the only product path is download, install and
 * restart. A network failure during discovery is fail-open so a CDN outage
 * cannot brick an otherwise valid signed installation.
 */
export class FabiMandatoryAppUpdater {

    constructor(protected readonly updater: AppUpdater = autoUpdater) { }

    async run(): Promise<void> {
        if (!this.shouldCheck()) {
            return;
        }
        this.configure();
        await enforceMandatoryUpdate(
            async () => {
                const result = await this.updater.checkForUpdates();
                return result?.isUpdateAvailable ? result.updateInfo : undefined;
            },
            info => this.blockForUpdate(info),
            error => console.warn('[fabi-update] vérification indisponible, démarrage conservé :', error)
        );
    }

    protected shouldCheck(): boolean {
        // Production cannot disable the mandatory gate with an environment
        // variable. Development opts in explicitly and uses dev-app-update.yml.
        return electron.app.isPackaged || process.env.FABI_FORCE_UPDATER === '1';
    }

    protected configure(): void {
        this.updater.autoDownload = false;
        this.updater.autoInstallOnAppQuit = false;
        this.updater.autoRunAppAfterInstall = true;
        this.updater.allowPrerelease = false;
        this.updater.allowDowngrade = false;
        this.updater.disableWebInstaller = true;
        this.updater.forceDevUpdateConfig = !electron.app.isPackaged;
        this.updater.requestHeaders = {
            'Cache-Control': 'no-cache',
            'X-Fabi-Version': electron.app.getVersion()
        };
        this.updater.logger = {
            info: (...args: unknown[]) => console.info('[fabi-update]', ...args),
            warn: (...args: unknown[]) => console.warn('[fabi-update]', ...args),
            error: (...args: unknown[]) => console.error('[fabi-update]', ...args),
            debug: (...args: unknown[]) => console.debug('[fabi-update]', ...args)
        };
    }

    protected blockForUpdate(info: UpdateInfo): Promise<never> {
        return new Promise<never>(() => {
            const dir = mkdtempSync(join(tmpdir(), 'fabi-update-'));
            const htmlPath = join(dir, 'update.html');
            const preloadPath = join(dir, 'preload.js');
            writeFileSync(htmlPath, UPDATE_HTML);
            writeFileSync(preloadPath, UPDATE_PRELOAD);

            const win = new electron.BrowserWindow({
                width: 520,
                height: 372,
                minWidth: 520,
                minHeight: 372,
                frame: false,
                resizable: false,
                center: true,
                show: false,
                backgroundColor: '#101114',
                title: 'Mise à jour de Fabi',
                webPreferences: {
                    preload: preloadPath,
                    contextIsolation: true,
                    nodeIntegration: false,
                    sandbox: true,
                    backgroundThrottling: false
                }
            });

            let busy = false;
            let downloaded = false;
            let installing = false;
            const send = (channel: string, payload?: unknown) => {
                if (!win.isDestroyed()) {
                    win.webContents.send(channel, payload);
                }
            };
            const onProgress = (progress: ProgressInfo) => {
                const percent = Math.max(0, Math.min(100, progress.percent));
                send('fabi-update:progress', {
                    percent,
                    bytesPerSecond: Math.max(0, progress.bytesPerSecond),
                    transferred: Math.max(0, progress.transferred),
                    total: Math.max(0, progress.total)
                });
                try { win.setProgressBar(percent / 100); } catch { /* best effort */ }
            };
            const onDownloaded = () => {
                downloaded = true;
                busy = false;
                send('fabi-update:ready');
                void install();
            };
            const onError = (error: Error) => {
                busy = false;
                installing = false;
                try { win.setProgressBar(-1); } catch { /* best effort */ }
                send('fabi-update:error', { message: error.message || 'La mise à jour a échoué.' });
            };
            const install = async () => {
                if (installing) {
                    return;
                }
                if (!downloaded) {
                    await download();
                    return;
                }
                installing = true;
                send('fabi-update:installing');
                try {
                    this.updater.quitAndInstall(false, true);
                } catch (error) {
                    onError(error instanceof Error ? error : new Error(String(error)));
                }
            };
            const download = async () => {
                if (busy || installing) {
                    return;
                }
                busy = true;
                send('fabi-update:downloading');
                try {
                    await this.updater.downloadUpdate();
                } catch (error) {
                    onError(error instanceof Error ? error : new Error(String(error)));
                }
            };

            this.updater.on('download-progress', onProgress);
            this.updater.on('update-downloaded', onDownloaded);
            this.updater.on('error', onError);
            electron.ipcMain.on('fabi-update:start', install);

            const cleanup = () => {
                electron.ipcMain.removeListener('fabi-update:start', install);
                this.updater.removeListener('download-progress', onProgress);
                this.updater.removeListener('update-downloaded', onDownloaded);
                this.updater.removeListener('error', onError);
                try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ }
            };
            win.once('ready-to-show', () => {
                win.show();
                send('fabi-update:available', {
                    currentVersion: electron.app.getVersion(),
                    nextVersion: info.version
                });
            });
            // No close-to-bypass once a newer authenticated release is known.
            win.on('close', event => {
                if (!installing) {
                    event.preventDefault();
                }
            });
            win.on('closed', cleanup);
            win.loadFile(htmlPath);
        });
    }
}

const UPDATE_PRELOAD = `
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('fabiUpdate', {
  start: () => ipcRenderer.send('fabi-update:start'),
  onAvailable: cb => ipcRenderer.on('fabi-update:available', (_event, value) => cb(value)),
  onDownloading: cb => ipcRenderer.on('fabi-update:downloading', () => cb()),
  onProgress: cb => ipcRenderer.on('fabi-update:progress', (_event, value) => cb(value)),
  onReady: cb => ipcRenderer.on('fabi-update:ready', () => cb()),
  onInstalling: cb => ipcRenderer.on('fabi-update:installing', () => cb()),
  onError: cb => ipcRenderer.on('fabi-update:error', (_event, value) => cb(value))
});
`;

const UPDATE_HTML = `<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root { color-scheme: dark; --bg:#101114; --surface:#17181c; --text:#e7e8eb;
    --muted:#9297a1; --faint:#666b75; --line:rgba(255,255,255,.1); --orange:#f06436; }
  * { box-sizing: border-box; }
  html, body { width:100%; height:100%; margin:0; overflow:hidden; background:var(--bg);
    color:var(--text); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
    -webkit-font-smoothing:antialiased; user-select:none; }
  main { -webkit-app-region:drag; height:100%; padding:38px 42px 32px; display:flex;
    flex-direction:column; border:1px solid var(--line); }
  header { display:flex; align-items:center; gap:14px; }
  .fox { width:46px; height:46px; image-rendering:pixelated; }
  h1 { margin:0; font-size:20px; font-weight:670; letter-spacing:-.025em; }
  .versions { margin-top:4px; color:var(--faint); font-size:11px; font-variant-numeric:tabular-nums; }
  .copy { margin:34px 0 0; max-width:390px; color:var(--muted); font-size:13px; line-height:1.55; }
  .track { height:3px; margin-top:28px; overflow:hidden; border-radius:2px; background:rgba(255,255,255,.08); }
  .bar { width:0; height:100%; background:var(--orange); transition:width .2s ease; }
  .status { min-height:17px; margin-top:10px; color:var(--faint); font-size:11px; }
  button { -webkit-app-region:no-drag; align-self:flex-start; min-width:132px; min-height:34px;
    margin-top:auto; padding:7px 14px; border:0; border-radius:6px; background:var(--orange);
    color:#fff; font:620 12px/1 inherit; cursor:pointer; }
  button:hover { background:#ff7547; }
  button:disabled { cursor:default; opacity:.52; }
  .error { color:#df7168; }
</style>
</head>
<body>
<main>
  <header>
    <img class="fox" src="${FABI_FOX_DATA_URI}" alt="">
    <div><h1>Une nouvelle version de Fabi est disponible</h1><div class="versions" id="versions">Vérification…</div></div>
  </header>
  <p class="copy" id="copy">Cette mise à jour est requise pour garder l’IDE, le protocole du swarm et le moteur compatibles.</p>
  <div class="track" aria-hidden="true"><div class="bar" id="bar"></div></div>
  <div class="status" id="status" role="status" aria-live="polite">Prête à télécharger.</div>
  <button id="action" type="button">Mettre à jour</button>
</main>
<script>
  const action = document.getElementById('action');
  const status = document.getElementById('status');
  const copy = document.getElementById('copy');
  const bar = document.getElementById('bar');
  const versions = document.getElementById('versions');
  const humanBytes = value => value > 1048576 ? (value / 1048576).toFixed(1) + ' Mio' : Math.round(value / 1024) + ' Kio';
  window.fabiUpdate.onAvailable(value => { versions.textContent = 'Fabi ' + value.currentVersion + '  →  ' + value.nextVersion; });
  window.fabiUpdate.onDownloading(() => { action.disabled = true; action.textContent = 'Téléchargement…'; status.className = 'status'; status.textContent = 'Téléchargement sécurisé en cours.'; });
  window.fabiUpdate.onProgress(value => { bar.style.width = value.percent.toFixed(1) + '%'; status.textContent = value.percent.toFixed(0) + '% · ' + humanBytes(value.transferred) + ' / ' + humanBytes(value.total); });
  window.fabiUpdate.onReady(() => { bar.style.width = '100%'; status.textContent = 'Téléchargement vérifié.'; });
  window.fabiUpdate.onInstalling(() => { action.disabled = true; action.textContent = 'Installation…'; status.textContent = 'Fabi va redémarrer automatiquement.'; copy.textContent = 'Installation de la version signée. Ne ferme pas l’application.'; });
  window.fabiUpdate.onError(value => { action.disabled = false; action.textContent = 'Réessayer'; status.className = 'status error'; status.textContent = value && value.message ? value.message : 'La mise à jour a échoué.'; });
  action.addEventListener('click', () => window.fabiUpdate.start());
</script>
</body>
</html>`;
